name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build_sonarqube:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full Git history is available

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y git

      - name: Fix File Permissions
        run: chmod -R 755 sonarqube-master  # Fix file permission issues

      - name: Build with Gradle and SonarQube Analysis
        run: |
          cd sonarqube-master
          ./gradlew build -Dsonar.log.level=INFO | tee build.log

      - name: Compress Build Log
        run: gzip -9 sonarqube-master/build.log

      - name: Upload Artifact (Build Log)
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: sonarqube-master/build.log.gz
          retention-days: 7
